version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client-samples"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: "go"
    directory: "/client-samples"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/code/gms-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: "maven"
    directory: "/code"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0