DROP TABLE gms_user;
DROP TABLE gms_api_key;
DROP TABLE gms_event;
DROP TABLE gms_keystore;
DROP TABLE gms_keystore_alias;
DROP TABLE gms_secret;
DROP TABLE gms_announcement;
DROP TABLE gms_message;
DROP TABLE gms_api_restriction;