CREATE TABLE gms_user (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	creation_date TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
	credential VARCHAR(255) DEFAULT NULL,
	email VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	role VARCHAR(255) NOT NULL,
	status VARCHAR(255) NOT NULL,
	user_name VARCHAR(255) NOT NULL,
	mfa_enabled SMALLINT NOT NULL DEFAULT 0,
	mfa_secret VARCHAR(32) NOT NULL,
	failed_attempts INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE gms_api_key (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	creation_date TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(255) DEFAULT NULL,
	status VARCHAR(255) NOT NULL,
	user_id BIGINT NOT NULL,
	value VARCHAR(512) NOT NULL
);

CREATE TABLE gms_event (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	event_date TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
	operation VARCHAR(255) DEFAULT NULL,
	target VARCHAR(255) DEFAULT NULL,
	user_id BIGINT NOT NULL
);

CREATE TABLE gms_keystore (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	creation_date TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
	credential VARCHAR(512) NOT NULL,
	description VARCHAR(255) DEFAULT NULL,
	file_name VARCHAR(255) DEFAULT NULL,
	status VARCHAR(255) NOT NULL,
	type VARCHAR(255) NOT NULL,
	user_id BIGINT DEFAULT NULL
);

CREATE TABLE gms_keystore_alias (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	keystore_id BIGINT DEFAULT NULL,
	alias VARCHAR(512) NOT NULL,
	alias_credential VARCHAR(512) NOT NULL,
	description VARCHAR(255) DEFAULT NULL,
	algorithm VARCHAR(64) DEFAULT NULL
);

CREATE TABLE gms_secret (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	creation_date TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
	keystore_alias_id BIGINT NOT NULL,
	last_rotated TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
	last_updated TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
	return_decrypted SMALLINT NOT NULL DEFAULT 1,
	rotation_enabled SMALLINT NOT NULL DEFAULT 1,
	rotation_period VARCHAR(255) NOT NULL,
	secret_id VARCHAR(255) NOT NULL,
	status VARCHAR(255) DEFAULT NULL,
	secret_type VARCHAR(255) NOT NULL,
	user_id BIGINT NOT NULL,
	value CLOB NOT NULL
);

CREATE TABLE gms_announcement (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	author_id BIGINT NOT NULL,
	announcement_date TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
	title VARCHAR(255) DEFAULT NULL,
	description VARCHAR(255) DEFAULT NULL
);

CREATE TABLE gms_message (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL,
	creation_date TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
	message VARCHAR(255) DEFAULT NULL,
	opened SMALLINT NOT NULL DEFAULT 0,
	action_path VARCHAR(255) DEFAULT NULL
);

CREATE TABLE gms_api_key_restriction (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	secret_id BIGINT DEFAULT NULL,
	api_key_id BIGINT NOT NULL,
	user_id BIGINT NOT NULL
);

CREATE TABLE gms_system_property (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	prop_key VARCHAR(255) DEFAULT NULL,
	prop_value VARCHAR(255) DEFAULT NULL,
	last_modified TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
);

CREATE TABLE gms_ip_restriction (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT DEFAULT NULL,
	secret_id BIGINT DEFAULT NULL,
	status VARCHAR(255) DEFAULT NULL,
	ip_pattern VARCHAR(255) DEFAULT NULL,
	allow SMALLINT NOT NULL DEFAULT 0,
	global SMALLINT NOT NULL DEFAULT 0,
	creation_date TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
	last_modified TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
);

CREATE TABLE gms_job (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    end_time TIMESTAMP DEFAULT NULL,
    duration SMALLINT DEFAULT NULL,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    message VARCHAR(255) DEFAULT NULL,
    correlation_id VARCHAR(255) NOT NULL
);

CREATE TABLE gms_system_attribute (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL
);

INSERT INTO gms_system_attribute (name, value) VALUES ('SYSTEM_STATUS', 'NEED_SETUP');