apiVersion: v1
kind: PersistentVolume
metadata:
  name: gms-keystores-pv
  labels:
    type: keystores
spec:
  #persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: //d/dev/projects/open-source/keystores/
    #type: Directory

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gms-ks-pv
  labels:
    type: ks
spec:
  #persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: //d/dev/projects/open-source/ks/
    #type: Directory

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gms-tempks-pv
  labels:
    type: tempks
spec:
  #persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: //d/dev/projects/open-source/temp-ks/
    #type: Directory