apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gms-tempks-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: tempks