name: Frontend code quality check

defaults:
  run:
    shell: bash
    working-directory: ./code/gms-frontend

on:
  pull_request:
  push:
    paths:
      - code/gms-frontend/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build with NPM
        run: npm install
      - name: Install Angular CLI
        run: npm install -g @angular/cli@latest
      - name: Run tests
        run: ng test
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2.0.2
