name: Backend code quality check

defaults:
  run:
    shell: bash
    working-directory: ./code/gms-backend

on:
  pull_request:
  push:
    paths:
      - code/gms-backend/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean verify -Pcodecov
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2.0.2
