name: Publish Java client library

defaults:
  run:
    shell: bash
    working-directory: client-libraries/java

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Java client library build and analysis"]
    branches: [main]
    types: 
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Prepare release
        run: mvn clean package -Pprepare-next-version -DskipTests=true
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update version to next snapshot
        run: mvn clean package -Pprepare-next-snapshot -DskipTests=true
      - name: Commit report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Version update"
          git push
