name: Publish Java client library

defaults:
  run:
    shell: bash
    working-directory: client-libraries/java

on:
  workflow_dispatch:
  #release:
  #  types: [created]
  workflow_run:
    workflows: ["Java client library build and analysis"]
    branches: [main]
    types: 
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}